name: aws_ec2_deployments_for_ec2instance
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  upload_S3_bucket:
    runs-on: ubuntu-latest
    steps:
    - name: Setup repo
      run: It also working fine dude
